export const FETCH_PROFILEDATA_SUCCESS = "FETCH_PROFILEDATA_SUCCESS"
export const FETCH_PROFILEDATA_FAILURE = "FETCH_PROFILEDATA_FAILURE"
export const FETCH_PROFILEDATA_REQUEST = "FETCH_PROFILEDATA_REQUEST"
export const TOGGLE_FOLLOW = "TOGGLE_FOLLOW"