export const FETCH_POSTSDATA_SUCCESS = "FETCH_POSTSDATA_SUCCESS"
export const FETCH_POSTSDATA_FAILURE = "FETCH_POSTSDATA_FAILURE"
export const FETCH_POSTSDATA_REQUEST = "FETCH_POSTSDATA_REQUEST"
export const TOGGLE_LIKE = "TOGGLE_LIKE"