export const FETCH_POSTSDATA_SUCCESS = "FETCH_POSTSDATA_SUCCESS";
export const FETCH_POSTSDATA_FAILURE = "FETCH_POSTSDATA_FAILURE";
export const FETCH_POSTSDATA_REQUEST = "FETCH_POSTSDATA_REQUEST";
export const FETCH_IGTVDATA_SUCCESS = "FETCH_IGTVDATA_SUCCESS";
export const FETCH_IGTVDATA_FAILURE = "FETCH_IGTVDATA_FAILURE";
export const FETCH_IGTVDATA_REQUEST = "FETCH_IGTVDATA_REQUEST";
export const CHANGE_CURRENT_TAB = "CHANGE_CURRENT_TAB"
